# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: python-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.py'
#    - '!exclude-me-dir/**'
#    - include-me.py
#    - include-me-dir/**

functions:

  # Samples for [Inputs]
  input1:
    handler: lambdas.Inputs.input1.lambdaFunc
    name: input-func-1
    events:
      - http:
          path: input/1
          method: GET
  input2:
    handler: lambdas.Inputs.input2.lambdaFunc
    name: input-func-2
    events:
      - http:
          path: input/2
          method: GET
  input3:
    handler: lambdas.Inputs.input3.lambdaFunc
    name: input-func-3
    events:
      - http:
          path: input/3
          method: POST
  input4:
    handler: lambdas.Inputs.input4.lambdaFunc
    name: input-func-4
    events:
      - http:
          path: input/4
          method: GET
  input5:
    handler: lambdas.Inputs.input5.lambdaFunc
    name: input-func-5
    events:
      - http:
          path: input/5
          method: GET


  # Samples for [Outputs]
  output1:
    handler: lambdas.Outputs.sample1.lambdaFunc
    name: output-func-1
    events:
      - http:
          path: output/1
          method: GET
  output2:
    handler: lambdas.Outputs.sample2.lambdaFunc
    name: output-func-2
    events:
      - http:
          path: output/2
          method: GET
  output3:
    handler: lambdas.Outputs.sample3.lambdaFunc
    name: output-func-3
    events:
      - http:
          path: output/3
          method: GET
  # Samples for [DynamoDB]
  dynamo1:
    handler: lambdas.DynamoDB.sample1.lambdaFunc
    name: dynamo-func-1
    events:
      - http:
          path: dynamo/1
          method: GET
  dynamo2:
    handler: lambdas.DynamoDB.sample2.lambdaFunc
    name: dynamo-func-2
    events:
      - http:
          path: dynamo/2
          method: GET
  dynamo3:
    handler: lambdas.DynamoDB.sample3.lambdaFunc
    name: dynamo-func-3
    events:
      - http:
          path: dynamo/3
          method: GET
  dynamo4:
    handler: lambdas.DynamoDB.sample4.lambdaFunc
    name: dynamo-func-4
    events:
      - http:
          path: dynamo/4
          method: GET
  dynamo5:
    handler: lambdas.DynamoDB.sample5.lambdaFunc
    name: dynamo-func-5
    events:
      - http:
          path: dynamo/5
          method: GET
  
  # Samples for [Unchecked_Input_for_Loop_Condition]
  input-loop1:
    handler: lambdas.Unchecked_Input_for_Loop_Condition.sample1.lambdaFunc
    name: input-loop-1
    events:
      - http:
          path: inloop/1
          method: GET

  input-loop2:
    handler: lambdas.Unchecked_Input_for_Loop_Condition.sample1.lambdaFuncTN
    name: input-loop-2
    events:
      - http:
          path: inloop/2
          method: GET
  
  
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - httpApi:
#          path: /users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-offline
  - serverless-dynamodb-local
