import json

# This is the default lambda function generated by serverless
def lambdaFunc(event, context):
 # Get the action parameter from the custom property
    action = context.client_context.custom
    # or from the custom as a dictionary
    action = context.client_context.custom['action']
    action = context.client_context.custom.get('action')
    action = context.client_context.custom.get('action', 'default')
    # Get the action parameter from the env property
    action = context.client_context.env
    # or from the env as a dictionary
    action = context.client_context.env['action']
    action = context.client_context.env.get('action')
    action = context.client_context.env.get('action', 'default')
    return 'ok'
