import json

# This is the default lambda function generated by serverless
def lambdaFunc(event, context):
    action = context.client_context.installation_id
    action = context.client_context.app_title
    action = context.client_context.app_version_name
    action = context.client_context.app_version_code
    action = context.client_context.app_package_name
    return 'ok'
